server:
  port: 8080


#数据源配置
spring:
  application:
    name: service
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型    为了去除一个烦人的Error而注掉
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://120.79.37.96:3306/testmyshop?useUnicode=true&characterEncoding=utf8             # 数据库名称
    username: root
    password: 1234
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间


#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatisConfig.xml        # mybatis配置文件所在路径
  type-aliases-package: com.bean           # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml   # mapper映射文件
